//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contrato
    {
        public int id_contrato { get; set; }
        public System.DateTime fecha_inicio { get; set; }
        public System.DateTime fecha_termino { get; set; }
        public string argumento { get; set; }
        public int Fk_id_usuario { get; set; }
        public int Fk_id_vehiculo { get; set; }
    
        public virtual Vehiculo Vehiculo { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
