//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehiculo
    {
        public Vehiculo()
        {
            this.Contrato = new HashSet<Contrato>();
        }
    
        public int id_vehiculo { get; set; }
        public string marca { get; set; }
        public string modelo { get; set; }
        public int anio { get; set; }
        public int nro_puertas { get; set; }
        public int nro_pasajeros { get; set; }
        public string trasmision { get; set; }
        public string imagen { get; set; }
    
        public virtual ICollection<Contrato> Contrato { get; set; }
    }
}
